apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: vault-k8s-workshop
servers: 1
agents: 5
kubeAPI:
  host: vault-k8s.workshops.utkusarioglu.com
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --tls-san=vault-k8s.workshops.utkusarioglu.com
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:0
      - arg: --node-name=server-0
        nodeFilters:
          - server:0
      - arg: --node-name=worker-0
        nodeFilters:
          - agent:0
      - arg: --node-name=worker-1
        nodeFilters:
          - agent:1
      - arg: --node-name=worker-2
        nodeFilters:
          - agent:2
      - arg: --node-name=worker-3
        nodeFilters:
          - agent:3
      - arg: --node-name=worker-4
        nodeFilters:
          - agent:4
    nodeLabels:
      - label: vault_in_k8s=true
        nodeFilters:
          - agent:2
      - label: vault_in_k8s=true
        nodeFilters:
          - agent:3
      - label: vault_in_k8s=true
        nodeFilters:
          - agent:4
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
