apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: tf-k8s-repo-template
servers: 1
agents: 2
kubeAPI:
  host: tf-k8s-repo-template.templates.utkusarioglu.com
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --tls-san=tf-k8s-repo-template.templates.utkusarioglu.com
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:0
      - arg: --node-name=server-0
        nodeFilters:
          - server:0
      - arg: --node-name=worker-0
        nodeFilters:
          - agent:0
      - arg: --node-name=worker-1
        nodeFilters:
          - agent:1
    nodeLabels:
      - label: k3d-node=0
        nodeFilters:
          - agent:0
      - label: k3d-node=1
        nodeFilters:
          - agent:1
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
